# For docs on this file, see:
#   https://dart.dev/guides/language/analysis-options
include: package:flutter_lints/flutter.yaml

linter:
  # For a list of all available lints, with docs, see:
  #   https://dart-lang.github.io/linter/lints/index.html.
  rules:
    no_literal_bool_comparisons: true
    prefer_relative_imports: true
